basePath: /
definitions:
  common.Response:
    properties:
      data: {}
      errors: {}
      message:
        type: string
      status:
        type: boolean
    type: object
  entity.Todos:
    properties:
      category:
        type: string
      createdAt:
        type: string
      deadline:
        type: string
      deletedAt:
        type: string
      description:
        type: string
      id:
        type: integer
      is_complete:
        type: boolean
      name:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Projek todo list untuk final projek pertama
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Go + Gin Todo API
  version: "1.0"
paths:
  /auth/sign-in:
    post:
      operationId: sign-in
      parameters:
      - description: email
        in: path
        name: email
        required: true
        type: string
      - description: password
        in: path
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.Response'
      summary: sign-in/login
  /auth/sign-up:
    post:
      operationId: sign-up
      parameters:
      - description: user ID
        in: path
        name: id
        required: true
        type: string
      - description: name
        in: path
        name: name
        required: true
        type: string
      - description: email
        in: path
        name: email
        required: true
        type: string
      - description: password
        in: path
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.Response'
      summary: sign-up/register
  /todos:
    get:
      operationId: get-todos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Todos'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.Response'
      summary: Gets all todo item
    post:
      operationId: create-todo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Todos'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.Response'
      summary: Create a todo item
  /todos/{id}:
    delete:
      operationId: delete-todo-by-id
      parameters:
      - description: todo ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.Response'
      summary: delete a todo item by ID
    get:
      operationId: get-todo-by-id
      parameters:
      - description: todo ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Todos'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.Response'
      summary: get a todo item by ID
    put:
      operationId: update-todo-by-id
      parameters:
      - description: todo ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: Todos
        "404":
          description: Not Found
          schema:
            type: Response
      summary: update a todo item by ID
swagger: "2.0"
